version: '3.8'

services:
  rag-api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - rag-api
    restart: unless-stopped